[package]
name = "screen_toggle"
version = "0.1.0"
authors = ["ardijanr <a.rexhaj@stud.uis.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.2.0", features = ["svg"] }
packer = "0.5"